spring:
  mail:
    host: smtp.qq.com
    username: 1272065161@qq.com
    password: vzljehwotmymfjih
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          port: 465
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
        display:
          sendmail: Java
          sendname: Spring Boot Email
